### ISSUE TITLE
actual.getTime is not a function

### ISSUE THREAD

**Issue by dman777** [mguterl/chai-datetime#30]
Set up:
```javascript
  "devDependencies": {
    "chai": "^3.5.0",
    "chai-datetime": "^1.4.1",
    "chai-spies": "^0.7.1",
    "mocha": "^3.3.0",
    "nock": "^9.0.13",
    "proxyquire": "^1.7.11",
    "sinon": "^2.1.0",
    "sinon-chai": "^2.9.0",
    "sinon-stub-promise": "^4.0.0"
  }
```
```javascript
chai = require('chai');
var sinonStubPromise = require('sinon-stub-promise');
var sinon = require('sinon');
sinonStubPromise(sinon);


chai.use(require('sinon-chai'));
chai.use(require('chai-datetime'));

global.should = chai.should();
global.sinon = sinon;
global.proxy = require('proxyquire');
global.nock = require('nock');
```
test:

```javascript
    it('should set normal alert time stamp', ()=> {
      normalAlertStatus.setLock();
      normalAlertStatus.lockTimeStamp.should.be.afterTime(222);
    });
```

result:

```
  1) foo When setting lock on normal alert should set normal alert time stamp:
     TypeError: actual.getTime is not a function
      at Object.chai.datetime.afterTime (node_modules/chai-datetime/chai-datetime.js:88:19)
      at Assertion.<anonymous> (node_modules/chai-datetime/chai-datetime.js:148:21)
      at Assertion.assert (node_modules/chai/lib/chai/utils/addChainableMethod.js:84:49)
      at Context.it (test/locks.js:33:49)

```

**Comment by mitchlloyd** [comment]
`afterTime` expects to get a `Date` object which has a `getTime` method, but it looks like you're passing a `Number`: `222`.

This, on the other hand, should work:

```js
it('should set normal alert time stamp', () => {
  normalAlertStatus.setLock();
  normalAlertStatus.lockTimeStamp.should.be.afterTime(new Date(222));
});
```

**Comment by dman777** [comment]
Getting this also with `afterDate` 

```
          const date = new Date(1900);
          colText.should.be.afterDate(date);
```

`date.getFullYear is not a function` ...
any ideas why?

**Comment by mguterl** [comment]
@dman777 - what type is colText? Judging by the variable name, maybe it is a string and not a date? This library performs no type coercion for you, make sure you use date objects on both values.
